cd /mnt/cgi_tech_team/scripts/DB/Dev/gold_config/logs
rm *.log
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34065.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33755.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7835.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34373.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8191.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34286.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8189.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7932.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8376.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34428.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33905.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34573.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34318.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8379.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34112.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_27426.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34185.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8403.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34394.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34287.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8407.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33750.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33119.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8375.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34582.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7963.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33806.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34411.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8572.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34769.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8571.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8573.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8574.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34773.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34770.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34667.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34660.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34655.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34666.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34839.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7689.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8576.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8188.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7933.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8380.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34355.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34661.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35093.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34664.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34669.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34626.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34663.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34665.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34379.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35100.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33541.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35039.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35038.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34817.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34602.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34570.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35004.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35005.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34581.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35132.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35131.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34967.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7199.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33761.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35031.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35206.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35208.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35186.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35159.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35205.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35151.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35264.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35144.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35189.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35329.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35340.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35167.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35335.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35338.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35158.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34791.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8924.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35322.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35339.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35179.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_9500.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35165.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35163.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35504.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35353.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35611.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35600.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35597.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35596.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35263.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35343.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35337.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35454.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35456.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35348.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_26532.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35572.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35157.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35341.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35602.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35390.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35160.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35500.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35521.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35567.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34821.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_9492.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox36 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35450.sql

