cd /mnt/cgi_tech_team/scripts/DB/Dev/gold_config/logs
rm *.log
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34665.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34379.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35100.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33541.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35039.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35038.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34817.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34602.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34570.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35004.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35005.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34581.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35132.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35131.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34967.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_7199.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_33761.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35031.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35206.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35208.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35186.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35159.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35205.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35151.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35264.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35144.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35189.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35329.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35340.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35167.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35335.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35338.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35158.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34791.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_8924.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35322.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35339.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35179.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_9500.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35165.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35163.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35353.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35504.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35611.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35600.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35597.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35596.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35263.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35343.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35337.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35454.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35456.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35348.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_26532.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35572.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35157.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35341.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35602.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35390.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35160.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35500.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35521.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35567.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_34821.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/VBAGOE_9492.sql
${ORACLE_HOME}/bin/sqlplus openffs/openffs_123@sandbox35 @/mnt/cgi_tech_team/scripts/DB/Dev/gold_config/sql/EMR2_35450.sql
