set timing on;
set define off;
set echo on;

spool /mnt/cgi_tech_team/scripts/DB/Dev/scrubbing/logs/03_SCRUB_Other_01.log;

select distinct count(ssn) from openffs.mf_vend where ssn_in = 'S' 
	union 
select distinct count(e.socl_scty_num) from openffs.mf_empl e where not exists (select 1 from openffs.mf_vend v where v.ssn_in = 'S' and trim(e.socl_scty_num) = trim(v.ssn))	and trim(e.socl_scty_num) is not null;



alter session force parallel ddl parallel 10;

-- PJB -- column is already indexed -- create index openffs.SSSN_ID_2 on openffs.AMS_SCTY_USER_SSSN                 	(	SSSN_ID                       	);
create index openffs.ISSN_CCS_MNTH_5 on openffs.MF_ACQ_CLSO_CKLS               (	ISSN_CCS_MNTH                 	);
create index openffs.ISSN_CCS_FCDT_6 on openffs.MF_ACQ_CLSO_CKLS               (	ISSN_CCS_FCDT                 	);
create index openffs.ISSN_CCS_ACDT_7 on openffs.MF_ACQ_CLSO_CKLS               (	ISSN_CCS_ACDT                 	);
create index openffs.ISSN_CCR_MNTH_8 on openffs.MF_ACQ_CLSO_CKLS               (	ISSN_CCR_MNTH                 	);
create index openffs.ISSN_CCR_FCDT_9 on openffs.MF_ACQ_CLSO_CKLS               (	ISSN_CCR_FCDT                 	);
create index openffs.ISSN_CCR_ACDT_10 on openffs.MF_ACQ_CLSO_CKLS                 (	ISSN_CCR_ACDT                 	);
create index openffs.SSN_12 on openffs.MF_ADDR_LEVL_VEND                  	      (	SSN                           	);
create index openffs.VEND_SSN_14 on openffs.MF_AG                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_16 on openffs.MF_AGRE                            	(	VEND_SSN                      	);
create index openffs.VEND_SSN_17 on openffs.MF_AGRE                            	(	DGGT_VEND_SSN                      	);
create index openffs.VEND_SSN_18 on openffs.MF_AGRE_INTN_DOC                   	(	VEND_SSN                      	);
create index openffs.VEND_SSN_20 on openffs.MF_AGRE_INTN_FRM                   	(	VEND_SSN                      	);
create index openffs.VEND_SSN_22 on openffs.MF_AGRE_XTRN_DOC                   	(	VEND_SSN                      	);
create index openffs.VEND_SSN_23 on openffs.MF_AGRE_XTRN_DOC                   	(	DGGT_VEND_SSN                      	);
create index openffs.VEND_SSN_24 on openffs.MF_AGRE_XTRN_FRM                   	(	VEND_SSN                      	);
create index openffs.VEND_SSN_25 on openffs.MF_AGRE_XTRN_FRM                   	(	DGGT_VEND_SSN                      	);
create index openffs.VEND_SSN_26 on openffs.MF_AG_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_30 on openffs.MF_AMD_DOC_SRCH                    	(	VEND_SSN                      	);
create index openffs.VEND_SSN_32 on openffs.MF_ANNC                            	(	VEND_SSN                      	);
create index openffs.VEND_SSN_34 on openffs.MF_ANNC_AMD                        	(	VEND_SSN                      	);
create index openffs.VEND_SSN_36 on openffs.MF_ANNC_FRM                        	(	VEND_SSN                      	);
create index openffs.VEND_SSN_38 on openffs.MF_ARCH_TJ                         	(	VEND_SSN                      	);
--PJB -- column does not exist -- create index openffs.VEND_SSN_39 on openffs.MF_ARCH_TJ                         	(	DGGT+VEND_SSN                      	);
create index openffs.VEND_SSN_40 on openffs.MF_ASDL                            	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_42 on openffs.MF_BD                              	(	DGGT_SSN                      	);
--create index openffs.VEND_SSN_44 on openffs.MF_BD                              	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_46 on openffs.MF_BD_AMD                          	(	DGGT_SSN                      	);
create index openffs.VEND_SSN_48 on openffs.MF_BD_AMD                          	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_52 on openffs.MF_BD_FORM                         	(	DGGT_SSN                      	);
create index openffs.VEND_SSN_54 on openffs.MF_BD_FORM                         	(	VEND_SSN                      	);
create index openffs.SSN_55 on openffs.MF_BD_PY_FRM_LN                    	      (	SSN                           	);
create index openffs.SSN_56 on openffs.MF_BD_PY_LN                        	      (	SSN                           	);

create index openffs.CUST_VEND_SSN_144 on openffs.MF_IA_DOC_LN                       	(	CUST_VEND_SSN                 	);
create index openffs.CUST_VEND_SSN_146 on openffs.MF_IA_FRM_LN                       	(	CUST_VEND_SSN                 	);
create index openffs.CUST_VEND_SSN_148 on openffs.MF_IA_LN                           	(	CUST_VEND_SSN                 	);
create index openffs.VEND_SSN_150 on openffs.MF_IC                              	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_151 on openffs.MF_IC                              	(	DGGT_SSN                      	);
create index openffs.CUST_VEND_SSN_154 on openffs.MF_ID_DOC_LN                       	(	CUST_VEND_SSN                 	);
create index openffs.CUST_VEND_SSN_156 on openffs.MF_ID_FRM_LN                       	(	CUST_VEND_SSN                 	);
create index openffs.CUST_VEND_SSN_158 on openffs.MF_ID_LN                           	(	CUST_VEND_SSN                 	);
create index openffs.VEND_SSN_160 on openffs.MF_IF                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_162 on openffs.MF_IF_FRM                          	(	VEND_SSN                      	);
create index openffs.RCPN_SSN_164 on openffs.MF_IF_FRM_LN                       	(	RCPN_SSN                      	);
create index openffs.RCPN_SSN_166 on openffs.MF_IF_LN                           	(	RCPN_SSN                      	);
create index openffs.VEND_SSN_168 on openffs.MF_II                              	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_170 on openffs.MF_II                              	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_172 on openffs.MF_II_FRM                          	(	DGGT_SSN                      	);
create index openffs.VEND_SSN_174 on openffs.MF_II_FRM                          	(	VEND_SSN                      	);
create index openffs.DGGT_SSN_200 on openffs.MF_IP_FRM                          	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_208 on openffs.MF_IV                              	(	DGGT_SSN                      	);
create index openffs.VEND_SSN_198 on openffs.MF_IP_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_202 on openffs.MF_IQ                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_210 on openffs.MF_IV                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_216 on openffs.MF_JV_FRM_LN                       	(	VEND_SSN                      	);
create index openffs.VEND_SSN_218 on openffs.MF_JV_LN                           	(	VEND_SSN                      	);
create index openffs.VEND_SSN_220 on openffs.MF_MC                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_222 on openffs.MF_MC_FRM                          	(	VEND_SSN                      	);
create index openffs.ALTP_SSN_283 on openffs.MF_QA                              	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_289 on openffs.MF_QA_AMD                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_293 on openffs.MF_QA_FRM                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_297 on openffs.MF_QO                              	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_303 on openffs.MF_QO_AMD                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_311 on openffs.MF_QO_FRM                          	(	ALTP_SSN                      	);
create index openffs.ALTR_VEND_SSN_238 on openffs.MF_OVRS_CSHR                   (	ALTR_VEND_SSN                 	);
create index openffs.DGGT_SSN_279 on openffs.MF_QA                              	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_285 on openffs.MF_QA_AMD                          	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_291 on openffs.MF_QA_FRM                          	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_299 on openffs.MF_QO                              	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_307 on openffs.MF_QO_AMD                          	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_309 on openffs.MF_QO_FRM                          	(	DGGT_SSN                      	);
create index openffs.PRNC_VEND_SSN_236 on openffs.MF_OVRS_CSHR                   (	PRNC_VEND_SSN                 	);
create index openffs.SSN_273 on openffs.MF_PY_STGN                         	    (	SSN                           	);
create index openffs.SSN_FL_274 on openffs.MF_PY_XWLK                         	  (	SSN_FL                        	);
create index openffs.SSN_FROM_277 on openffs.MF_PY_XWLK_DTAL                    	(	SSN_FROM                      	);
create index openffs.SSN_OPER_276 on openffs.MF_PY_XWLK_DTAL                    	(	SSN_OPER                      	);
create index openffs.SSN_TO_275 on openffs.MF_PY_XWLK_DTAL                    	  (	SSN_TO                        	);
create index openffs.VEND_SSN_232 on openffs.MF_NV                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_234 on openffs.MF_NV_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_235 on openffs.MF_NV_ACTG_FRM_LN                          	(	BUYR_VEND_SSN                      	);
create index openffs.VEND_SSN_236 on openffs.MF_NV_ACTG_FRM_LN                          	(	SLR_VEND_SSN                      	);
create index openffs.VEND_SSN_237 on openffs.MF_NV_ACTG_LN                          	(	BUYR_VEND_SSN                      	);
create index openffs.VEND_SSN_238 on openffs.MF_NV_ACTG_LN                          	(	SLR_VEND_SSN                      	);
create index openffs.VEND_SSN_248 on openffs.MF_PERF_EVAL                       	(	VEND_SSN                      	);
create index openffs.VEND_SSN_249 on openffs.MF_PGIB_STGN                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_250 on openffs.MF_PGIB_STGN                          	(	REF_VEND_SSN                      	);
create index openffs.VEND_SSN_251 on openffs.MF_PGIB_XWLK_DTAL                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_252 on openffs.MF_PIR_SUMR                              	(	PIR_VEND_SSN                      	);
create index openffs.VEND_SSN_253 on openffs.MF_PRTST                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_254 on openffs.MF_PY_ACTY                          	(	SSN                      	);
create index openffs.VEND_SSN_281 on openffs.MF_QA                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_287 on openffs.MF_QA_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_295 on openffs.MF_QA_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_301 on openffs.MF_QO                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_305 on openffs.MF_QO_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_313 on openffs.MF_QO_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_315 on openffs.MF_QS                              	(	VEND_SSN                      	);

create index openffs.ALTP_SSN_351 on openffs.MF_TA                              	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_357 on openffs.MF_TA_AMD                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_361 on openffs.MF_TA_FRM                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_379 on openffs.MF_TG                              	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_383 on openffs.MF_TG_AMD                          	(	ALTP_SSN                      	);
create index openffs.ALTP_SSN_389 on openffs.MF_TG_FRM                          	(	ALTP_SSN                      	);
create index openffs.DGGT_SSN_377 on openffs.MF_TG                              	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_381 on openffs.MF_TG_AMD                          	(	DGGT_SSN                      	);
create index openffs.DGGT_SSN_387 on openffs.MF_TG_FRM                          	(	DGGT_SSN                      	);
create index openffs.SSN_348 on openffs.MF_SV_PY_FRM_LN                    	    (	SSN                           	);
create index openffs.SSN_349 on openffs.MF_SV_PY_LN                        	    (	SSN                           	);
create index openffs.VEND_SSN_317 on openffs.MF_QS_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_319 on openffs.MF_QS_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_321 on openffs.MF_QS_VEND                         	(	VEND_SSN                      	);
create index openffs.VEND_SSN_323 on openffs.MF_QS_VEND_AMD                     	(	VEND_SSN                      	);
create index openffs.VEND_SSN_325 on openffs.MF_QS_VEND_FRM                     	(	VEND_SSN                      	);
create index openffs.VEND_SSN_329 on openffs.MF_RCON_ITEM_TYPE                  	(	VEND_SSN                      	);
create index openffs.VEND_SSN_331 on openffs.MF_RCON_ITM                        	(	VEND_SSN                      	);
create index openffs.VEND_SSN_335 on openffs.MF_RS                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_337 on openffs.MF_RS_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_339 on openffs.MF_SUG_VEND                        	(	VEND_SSN                      	);
create index openffs.VEND_SSN_341 on openffs.MF_SUG_VEND_AMD                    	(	VEND_SSN                      	);
create index openffs.VEND_SSN_343 on openffs.MF_SUG_VEND_FRM                    	(	VEND_SSN                      	);
create index openffs.VEND_SSN_345 on openffs.MF_SV_FRM_LN                       	(	VEND_SSN                      	);
create index openffs.VEND_SSN_353 on openffs.MF_TA                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_355 on openffs.MF_TA_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_359 on openffs.MF_TA_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_363 on openffs.MF_TC                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_365 on openffs.MF_TC_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_367 on openffs.MF_TC_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_369 on openffs.MF_TECH_EVAL                       	(	VEND_SSN                      	);
create index openffs.VEND_SSN_371 on openffs.MF_TECH_EVAL_CRTN                  	(	VEND_SSN                      	);
create index openffs.VEND_SSN_373 on openffs.MF_TECH_EVAL_UNSL_LN       	(	VEND_SSN                      	);
create index openffs.VEND_SSN_375 on openffs.MF_TG                              	(	VEND_SSN                      	);
create index openffs.VEND_SSN_385 on openffs.MF_TG_AMD                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_391 on openffs.MF_TG_FRM                          	(	VEND_SSN                      	);
create index openffs.VEND_SSN_395 on openffs.MF_TI                              	(	VEND_SSN                      	);



--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

declare
   counter INTEGER := 0;
   --seedval NUMBER(9,0) := 123400000;
   oldnum CHAR(9);
   v_newnum varCHAR(9);
   cursor allnums is select distinct ssn, newnum from openffs.SSN_XWLK where newnum is not null 
   										union 
   									select distinct e.socl_scty_num, null from openffs.mf_empl e where not exists (select 1 from openffs.ssn_xwlk v where trim(e.socl_scty_num) = trim(v.ssn))	and trim(e.socl_scty_num) is not null;
   pointer allnums%ROWTYPE;
begin
   for pointer in allnums
      loop
        counter := counter+1;
        oldnum  := SUBSTR(pointer.ssn,1,9);
        --newnum  := LTRIM(TO_CHAR(seedval + counter, '999999999'));
        v_newnum  := pointer.newnum;
        
update openffs.AMS_SCTY_USER_SSSN                   set SSSN_ID                       = v_newnum where SSSN_ID                = oldnum;
commit;
commit;
update openffs.MF_ADDR_LEVL_VEND                    set SSN                           = v_newnum where SSN                    = oldnum;
commit;
update openffs.MF_AG                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE                              set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE                              set DGGT_VEND_SSN                      = v_newnum where DGGT_VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_INTN_DOC                     set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_INTN_FRM                     set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_XTRN_DOC                     set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_XTRN_DOC                     set DGGT_VEND_SSN                      = v_newnum where DGGT_VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_XTRN_FRM                     set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AGRE_XTRN_FRM                     set DGGT_VEND_SSN                      = v_newnum where DGGT_VEND_SSN               = oldnum;
commit;
update openffs.MF_AG_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_AMD_DOC_SRCH                      set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_ANNC                              set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_ANNC_AMD                          set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_ANNC_FRM                          set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_ARCH_TJ                           set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_ASDL                              set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_BD                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_BD                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_BD_AMD                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_BD_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_BD_FORM                           set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_BD_FORM                           set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_BD_PY_FRM_LN                      set SSN                           = v_newnum where SSN                    = oldnum;
commit;
update openffs.MF_BD_PY_LN                          set SSN                           = v_newnum where SSN                    = oldnum;
commit;
   end loop;
end;
/


declare
   counter INTEGER := 0;
   --seedval NUMBER(9,0) := 123400000;
   oldnum CHAR(9);
   v_newnum varCHAR(9);
   cursor allnums is select distinct ssn, newnum from openffs.SSN_XWLK where newnum is not null 
   										union 
   					select distinct e.socl_scty_num, null from openffs.mf_empl e where not exists (select 1 from openffs.ssn_xwlk v where trim(e.socl_scty_num) = trim(v.ssn))	and trim(e.socl_scty_num) is not null;
   pointer allnums%ROWTYPE;
begin
   for pointer in allnums
      loop
        counter := counter+1;
        oldnum  := SUBSTR(pointer.ssn,1,9);
        --newnum  := LTRIM(TO_CHAR(seedval + counter, '999999999'));
        v_newnum  := pointer.newnum;
update openffs.MF_IA_DOC_LN                         set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_IA_FRM_LN                         set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_IA_LN                             set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_IC                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IC                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_ID_DOC_LN                         set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_ID_FRM_LN                         set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_ID_LN                             set CUST_VEND_SSN                 = v_newnum where CUST_VEND_SSN          = oldnum;
commit;
update openffs.MF_IF                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IF_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IF_FRM_LN                         set RCPN_SSN                      = v_newnum where RCPN_SSN               = oldnum;
commit;
update openffs.MF_IF_LN                             set RCPN_SSN                      = v_newnum where RCPN_SSN               = oldnum;
commit;
update openffs.MF_II                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_II                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_II_FRM                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_II_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IP_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IP_FRM                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_IQ                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_IV                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_IV                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_JV_FRM_LN                         set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_JV_LN                             set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_MC                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_MC_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
   end loop;
end;
/



declare
   counter INTEGER := 0;
   --seedval NUMBER(9,0) := 123400000;
   oldnum CHAR(9);
   v_newnum varCHAR(9);
   cursor allnums is select distinct ssn, newnum from openffs.SSN_XWLK where newnum is not null 
   										union 
   									select distinct e.socl_scty_num, null from openffs.mf_empl e where not exists (select 1 from openffs.ssn_xwlk v where trim(e.socl_scty_num) = trim(v.ssn))	and trim(e.socl_scty_num) is not null;
   pointer allnums%ROWTYPE;
begin
   for pointer in allnums
      loop
        counter := counter+1;
        oldnum  := SUBSTR(pointer.ssn,1,9);
        --newnum  := LTRIM(TO_CHAR(seedval + counter, '999999999'));
        v_newnum  := pointer.newnum;

update openffs.MF_NV                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_NV_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_NV_ACTG_FRM_LN                            set BUYR_VEND_SSN                      = v_newnum where BUYR_VEND_SSN               = oldnum;
commit;
update openffs.MF_NV_ACTG_FRM_LN                            set SLR_VEND_SSN                      = v_newnum where SLR_VEND_SSN               = oldnum;
commit;
update openffs.MF_NV_ACTG_LN                            set BUYR_VEND_SSN                      = v_newnum where BUYR_VEND_SSN               = oldnum;
commit;
update openffs.MF_NV_ACTG_LN                            set SLR_VEND_SSN                      = v_newnum where SLR_VEND_SSN               = oldnum;
commit;
update openffs.MF_OVRS_CSHR                         set PRNC_VEND_SSN                 = v_newnum where PRNC_VEND_SSN          = oldnum;
commit;
update openffs.MF_OVRS_CSHR                         set ALTR_VEND_SSN                 = v_newnum where ALTR_VEND_SSN          = oldnum;
commit;
update openffs.MF_PERF_EVAL                         set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_PGIB_STGN                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_PGIB_STGN                                set REF_VEND_SSN                      = v_newnum where REF_VEND_SSN               = oldnum;
commit;
update openffs.MF_PGIB_XWLK_DTAL                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_PIR_SUMR                            set PIR_VEND_SSN                      = v_newnum where PIR_VEND_SSN               = oldnum;
commit;
update openffs.MF_PRTST                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_PY_ACTY                            set SSN                      = v_newnum where SSN               = oldnum;
commit;
update openffs.MF_PY_STGN                           set SSN                           = v_newnum where SSN                    = oldnum;
commit;
--PJB -- no need to update a Flag -- update openffs.MF_PY_XWLK                           set SSN_FL                        = v_newnum where SSN_FL                 = oldnum;
--PJB -- no need to update a Flag -- commit;
update openffs.MF_PY_XWLK_DTAL                      set SSN_TO                        = v_newnum where SSN_TO                 = oldnum;
commit;
update openffs.MF_PY_XWLK_DTAL                      set SSN_OPER                      = v_newnum where SSN_OPER               = oldnum;
commit;
update openffs.MF_PY_XWLK_DTAL                      set SSN_FROM                      = v_newnum where SSN_FROM               = oldnum;
commit;
update openffs.MF_QA                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QA                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QA                                set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QA_AMD                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QA_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QA_AMD                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QA_FRM                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QA_FRM                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QA_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QO                                set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QO                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QO                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QO_AMD                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QO_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QO_AMD                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QO_FRM                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_QO_FRM                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_QO_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QS                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
   end loop;
end;
/




declare
   counter INTEGER := 0;
   --seedval NUMBER(9,0) := 123400000;
   oldnum CHAR(9);
   v_newnum varCHAR(9);
   cursor allnums is select distinct ssn, newnum from openffs.SSN_XWLK where newnum is not null 
   										union 
   									select distinct e.socl_scty_num, null from openffs.mf_empl e where not exists (select 1 from openffs.ssn_xwlk v where trim(e.socl_scty_num) = trim(v.ssn))	and trim(e.socl_scty_num) is not null;
   pointer allnums%ROWTYPE;
begin
   for pointer in allnums
      loop
        counter := counter+1;
        oldnum  := SUBSTR(pointer.ssn,1,9);
        --newnum  := LTRIM(TO_CHAR(seedval + counter, '999999999'));
        v_newnum  := pointer.newnum;

update openffs.MF_QS_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QS_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QS_VEND                           set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QS_VEND_AMD                       set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_QS_VEND_FRM                       set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_RCON_ITEM_TYPE                    set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_RCON_ITM                          set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_RS                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_RS_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_SUG_VEND                          set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_SUG_VEND_AMD                      set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_SUG_VEND_FRM                      set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_SV_FRM_LN                         set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_SV_PY_FRM_LN                      set SSN                           = v_newnum where SSN                    = oldnum;
commit;
update openffs.MF_SV_PY_LN                          set SSN                           = v_newnum where SSN                    = oldnum;
commit;
update openffs.MF_TA                                set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TA                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TA_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TA_AMD                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TA_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TA_FRM                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TC                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TC_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TC_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TECH_EVAL                         set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TECH_EVAL_CRTN                    set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TECH_EVAL_UNSL_LN         set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TG                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TG                                set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_TG                                set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TG_AMD                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_TG_AMD                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TG_AMD                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TG_FRM                            set DGGT_SSN                      = v_newnum where DGGT_SSN               = oldnum;
commit;
update openffs.MF_TG_FRM                            set ALTP_SSN                      = v_newnum where ALTP_SSN               = oldnum;
commit;
update openffs.MF_TG_FRM                            set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
commit;
update openffs.MF_TI                                set VEND_SSN                      = v_newnum where VEND_SSN               = oldnum;
        commit;
commit;
   end loop;
end;
/


--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

--PJB -- for any records that are not on Vendor table and are not 999 we'll just update to be 888888888
update openffs.AMS_SCTY_USER_SSSN                   set SSSN_ID                       = '888888888' where SSSN_ID          is not null and substr(SSSN_ID,1,3) not in ('123','234','999');
update openffs.MF_ADDR_LEVL_VEND                    set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_AG                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE                              set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE                              set DGGT_VEND_SSN                      = '888888888' where DGGT_VEND_SSN         is not null and substr(DGGT_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_INTN_DOC                     set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_INTN_FRM                     set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_XTRN_DOC                     set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_XTRN_DOC                     set DGGT_VEND_SSN                      = '888888888' where DGGT_VEND_SSN         is not null and substr(DGGT_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_XTRN_FRM                     set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AGRE_XTRN_FRM                     set DGGT_VEND_SSN                      = '888888888' where DGGT_VEND_SSN         is not null and substr(DGGT_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AG_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_AMD_DOC_SRCH                      set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ANNC                              set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ANNC_AMD                          set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ANNC_FRM                          set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ARCH_TJ                           set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
--PJB -- column does not exist -- update openffs.MF_ARCH_TJ                           set DGGT_VEND_SSN                      = '888888888' where DGGT_VEND_SSN         is not null and substr(DGGT_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ASDL                              set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_AMD                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_FORM                           set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_FORM                           set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_PY_FRM_LN                      set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_BD_PY_LN                          set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_IA_DOC_LN                         set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IA_FRM_LN                         set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IA_LN                             set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IC                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IC                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_ID_DOC_LN                         set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ID_FRM_LN                         set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_ID_LN                             set CUST_VEND_SSN                 = '888888888' where CUST_VEND_SSN    is not null and substr(CUST_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IF                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IF_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IF_FRM_LN                         set RCPN_SSN                      = '888888888' where RCPN_SSN         is not null and substr(RCPN_SSN,1,3) not in ('123','234','999');
update openffs.MF_IF_LN                             set RCPN_SSN                      = '888888888' where RCPN_SSN         is not null and substr(RCPN_SSN,1,3) not in ('123','234','999');
update openffs.MF_II                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_II                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_II_FRM                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_II_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IP_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IP_FRM                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_IQ                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_IV                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_IV                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_JV_FRM_LN                         set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_JV_LN                             set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_MC                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_MC_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV_ACTG_FRM_LN                            set BUYR_VEND_SSN                      = '888888888' where BUYR_VEND_SSN         is not null and substr(BUYR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV_ACTG_FRM_LN                            set SLR_VEND_SSN                      = '888888888' where SLR_VEND_SSN         is not null and substr(SLR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV_ACTG_LN                            set BUYR_VEND_SSN                      = '888888888' where BUYR_VEND_SSN         is not null and substr(BUYR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_NV_ACTG_LN                            set SLR_VEND_SSN                      = '888888888' where SLR_VEND_SSN         is not null and substr(SLR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_OVRS_CSHR                         set PRNC_VEND_SSN                 = '888888888' where PRNC_VEND_SSN    is not null and substr(PRNC_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_OVRS_CSHR                         set ALTR_VEND_SSN                 = '888888888' where ALTR_VEND_SSN    is not null and substr(ALTR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PERF_EVAL                         set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PGIB_STGN                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PGIB_STGN                                set REF_VEND_SSN                      = '888888888' where REF_VEND_SSN         is not null and substr(REF_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PGIB_XWLK_DTAL                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PIR_SUMR                            set PIR_VEND_SSN                      = '888888888' where PIR_VEND_SSN         is not null and substr(PIR_VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PRTST                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_PY_ACTY                            set SSN                      = '888888888' where SSN         is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_PY_STGN                           set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
--PJB -- no need to update a Flag -- update openffs.MF_PY_XWLK                           set SSN_FL                        = '888888888' where SSN_FL           is not null and substr(SSN_FL,1,3) not in ('123','234','999');
update openffs.MF_PY_XWLK_DTAL                      set SSN_TO                        = '888888888' where SSN_TO           is not null and substr(SSN_TO,1,3) not in ('123','234','999');
update openffs.MF_PY_XWLK_DTAL                      set SSN_OPER                      = '888888888' where SSN_OPER         is not null and substr(SSN_OPER,1,3) not in ('123','234','999');
update openffs.MF_PY_XWLK_DTAL                      set SSN_FROM                      = '888888888' where SSN_FROM         is not null and substr(SSN_FROM,1,3) not in ('123','234','999');
update openffs.MF_QA                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA                                set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_AMD                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_AMD                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_FRM                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_FRM                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QA_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO                                set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_AMD                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_AMD                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_FRM                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_FRM                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_QO_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS_VEND                           set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS_VEND_AMD                       set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_QS_VEND_FRM                       set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_RCON_ITEM_TYPE                    set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_RCON_ITM                          set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_RS                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_RS_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_SUG_VEND                          set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_SUG_VEND_AMD                      set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_SUG_VEND_FRM                      set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_SV_FRM_LN                         set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_SV_PY_FRM_LN                      set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_SV_PY_LN                          set SSN                           = '888888888' where SSN              is not null and substr(SSN,1,3) not in ('123','234','999');
update openffs.MF_TA                                set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TA                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TA_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TA_AMD                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TA_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TA_FRM                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TC                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TC_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TC_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TECH_EVAL                         set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TECH_EVAL_CRTN                    set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TECH_EVAL_UNSL_LN         set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG                                set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_AMD                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_AMD                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_AMD                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_FRM                            set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_FRM                            set ALTP_SSN                      = '888888888' where ALTP_SSN         is not null and substr(ALTP_SSN,1,3) not in ('123','234','999');
update openffs.MF_TG_FRM                            set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
--PJB -- column does not exist -- update openffs.MF_TI                                set DGGT_SSN                      = '888888888' where DGGT_SSN         is not null and substr(DGGT_SSN,1,3) not in ('123','234','999');
update openffs.MF_TI                                set VEND_SSN                      = '888888888' where VEND_SSN         is not null and substr(VEND_SSN,1,3) not in ('123','234','999');
commit;

--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
--//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

-- PJB -- column is already indexed -- drop index openffs.SSSN_ID_2               ;
drop index openffs.ISSN_CCS_MNTH_5         ;
drop index openffs.ISSN_CCS_FCDT_6         ;
drop index openffs.ISSN_CCS_ACDT_7         ;
drop index openffs.ISSN_CCR_MNTH_8         ;
drop index openffs.ISSN_CCR_FCDT_9         ;
drop index openffs.ISSN_CCR_ACDT_10        ;
drop index openffs.SSN_12                  ;
drop index openffs.VEND_SSN_14             ;
drop index openffs.VEND_SSN_16             ;
drop index openffs.VEND_SSN_17             ;
drop index openffs.VEND_SSN_18             ;
drop index openffs.VEND_SSN_20             ;
drop index openffs.VEND_SSN_22             ;
drop index openffs.VEND_SSN_23             ;
drop index openffs.VEND_SSN_24             ;
drop index openffs.VEND_SSN_25             ;
drop index openffs.VEND_SSN_26             ;
drop index openffs.VEND_SSN_30             ;
drop index openffs.VEND_SSN_32             ;
drop index openffs.VEND_SSN_34             ;
drop index openffs.VEND_SSN_36             ;
drop index openffs.VEND_SSN_38             ;
drop index openffs.VEND_SSN_40             ;
drop index openffs.DGGT_SSN_42             ;
--drop index openffs.VEND_SSN_44             ;
drop index openffs.DGGT_SSN_46             ;
drop index openffs.VEND_SSN_48             ;
drop index openffs.DGGT_SSN_52             ;
drop index openffs.VEND_SSN_54             ;
drop index openffs.SSN_55                  ;
drop index openffs.SSN_56                  ;

drop index openffs.CUST_VEND_SSN_144       ;
drop index openffs.CUST_VEND_SSN_146       ;
drop index openffs.CUST_VEND_SSN_148       ;
drop index openffs.CUST_VEND_SSN_154       ;
drop index openffs.CUST_VEND_SSN_156       ;
drop index openffs.CUST_VEND_SSN_158       ;
drop index openffs.DGGT_SSN_170            ;
drop index openffs.DGGT_SSN_172            ;
drop index openffs.DGGT_SSN_200            ;
drop index openffs.DGGT_SSN_208            ;
drop index openffs.RCPN_SSN_164            ;
drop index openffs.RCPN_SSN_166            ;
drop index openffs.VEND_SSN_150            ;
drop index openffs.DGGT_SSN_151            ;
drop index openffs.VEND_SSN_160            ;
drop index openffs.VEND_SSN_162            ;
drop index openffs.VEND_SSN_168            ;
drop index openffs.VEND_SSN_174            ;
drop index openffs.VEND_SSN_198            ;
drop index openffs.VEND_SSN_202            ;
drop index openffs.VEND_SSN_210            ;
drop index openffs.VEND_SSN_216            ;
drop index openffs.VEND_SSN_218            ;
drop index openffs.VEND_SSN_220            ;
drop index openffs.VEND_SSN_222            ;
drop index openffs.ALTP_SSN_283            ;
drop index openffs.ALTP_SSN_289            ;
drop index openffs.ALTP_SSN_293            ;
drop index openffs.ALTP_SSN_297            ;
drop index openffs.ALTP_SSN_303            ;
drop index openffs.ALTP_SSN_311            ;
drop index openffs.ALTR_VEND_SSN_238       ;
drop index openffs.DGGT_SSN_279            ;
drop index openffs.DGGT_SSN_285            ;
drop index openffs.DGGT_SSN_291            ;
drop index openffs.DGGT_SSN_299            ;
drop index openffs.DGGT_SSN_307            ;
drop index openffs.DGGT_SSN_309            ;
drop index openffs.PRNC_VEND_SSN_236       ;
drop index openffs.SSN_273                 ;
drop index openffs.SSN_FL_274              ;
drop index openffs.SSN_FROM_277            ;
drop index openffs.SSN_OPER_276            ;
drop index openffs.SSN_TO_275              ;
drop index openffs.VEND_SSN_232            ;
drop index openffs.VEND_SSN_234            ;
drop index openffs.VEND_SSN_235            ;
drop index openffs.VEND_SSN_236            ;
drop index openffs.VEND_SSN_237            ;
drop index openffs.VEND_SSN_238            ;
drop index openffs.VEND_SSN_248            ;
drop index openffs.VEND_SSN_249            ;
drop index openffs.VEND_SSN_250            ;
drop index openffs.VEND_SSN_251            ;
drop index openffs.VEND_SSN_252            ;
drop index openffs.VEND_SSN_253            ;
drop index openffs.VEND_SSN_254            ;
drop index openffs.VEND_SSN_281            ;
drop index openffs.VEND_SSN_287            ;
drop index openffs.VEND_SSN_295            ;
drop index openffs.VEND_SSN_301            ;
drop index openffs.VEND_SSN_305            ;
drop index openffs.VEND_SSN_313            ;
drop index openffs.VEND_SSN_315            ;

drop index openffs.ALTP_SSN_351            ;
drop index openffs.ALTP_SSN_357            ;
drop index openffs.ALTP_SSN_361            ;
drop index openffs.ALTP_SSN_379            ;
drop index openffs.ALTP_SSN_383            ;
drop index openffs.ALTP_SSN_389            ;
drop index openffs.DGGT_SSN_377            ;
drop index openffs.DGGT_SSN_381            ;
drop index openffs.DGGT_SSN_387            ;
drop index openffs.SSN_348                 ;
drop index openffs.SSN_349                 ;
drop index openffs.VEND_SSN_317            ;
drop index openffs.VEND_SSN_319            ;
drop index openffs.VEND_SSN_321            ;
drop index openffs.VEND_SSN_323            ;
drop index openffs.VEND_SSN_325            ;
drop index openffs.VEND_SSN_329            ;
drop index openffs.VEND_SSN_331            ;
drop index openffs.VEND_SSN_335            ;
drop index openffs.VEND_SSN_337            ;
drop index openffs.VEND_SSN_339            ;
drop index openffs.VEND_SSN_341            ;
drop index openffs.VEND_SSN_343            ;
drop index openffs.VEND_SSN_345            ;
drop index openffs.VEND_SSN_353            ;
drop index openffs.VEND_SSN_355            ;
drop index openffs.VEND_SSN_359            ;
drop index openffs.VEND_SSN_363            ;
drop index openffs.VEND_SSN_365            ;
drop index openffs.VEND_SSN_367            ;
drop index openffs.VEND_SSN_369            ;
drop index openffs.VEND_SSN_371            ;
drop index openffs.VEND_SSN_373            ;
drop index openffs.VEND_SSN_375            ;
drop index openffs.VEND_SSN_385            ;
drop index openffs.VEND_SSN_391            ;
drop index openffs.VEND_SSN_395            ;

commit;
spool off;
exit;
