OPTIONS (SKIP=1)
Load DATA  
INFILE '/mnt/cgi_tech_team/scripts/DB/Dev/sqlldr/csv/VA_ACS_PPA_PROG_XWLK_DATA_TABLE.csv'
BADFILE '/mnt/cgi_tech_team/scripts/DB/Dev/sqlldr/logs/VA_ACS_PPA_PROG_XWLK_DATA_TABLE.bad'
DISCARDFILE '/mnt/cgi_tech_team/scripts/DB/Dev/sqlldr/logs/VA_ACS_PPA_PROG_XWLK_DATA_TABLE_discard.csv'
TRUNCATE 
INTO TABLE VA_ACS_PROG_XWLK
fields terminated by ',' optionally enclosed by '"'
(
FMS_FUND TERMINATED BY ',',
FMS_STATION TERMINATED BY ',',
FMS_STATION_NAME TERMINATED BY ',',
FMS_COST_CENTER TERMINATED BY ',',
FMS_COST_CENTER_NAME TERMINATED BY ',',
IFAMS_PARTITION TERMINATED BY ',',
IFAMS_BUDGET_PROGRAM_CODE TERMINATED BY ',',
IFAMS_BUDGET_PROGRAM_NAME TERMINATED BY ',',
IFAMS_VA_PROGRAM_CODE TERMINATED BY ',',
IFAMS_VA_PROGRAM_NAME
)


